function price_determinant_plt(P_max_EU,t_path,ref_path,label)
    
    figure()
    yline(P_max_EU,'Color','b','LineStyle','--')
    hold on
    yline(0,'Color','b','LineStyle','--')
    hold on 
    h1=fill([t_path fliplr(t_path)], ...
            [P_max_EU*ones(size(t_path)) 4.0*ones(size(t_path))], ...
            [1 0.7 0.7], ...
            'EdgeColor','none','FaceAlpha',0.4);
    hold on 
    h2=fill([t_path fliplr(t_path)], ...
            [0*ones(size(t_path)) P_max_EU*ones(size(t_path))], ...
            [1 1 0.7], ...
            'EdgeColor','none','FaceAlpha',0.3);
    hold on 
    h3=fill([t_path fliplr(t_path)], ...
            [-0.5*ones(size(t_path)) 0*ones(size(t_path))], ...
            [0.75 0.95 0.75], ...
            'EdgeColor','none','FaceAlpha',0.4);
    hold on
    h4=plot(t_path,ref_path, 'Color', "black");
    yyaxis right
    set(gca,'YColor','b')
    ylim([-0.5 4.0])
    yticks([0 P_max_EU])
    yticklabels({'0','a'})
    legend([h1 h2 h3 h4], ...
           {'$s_H$', '$s_M$', '$s_L$', label}, ...
           'Interpreter','latex', ...
           'Location','northwest', ...
           'FontSize',12)

end
