function write_summary_outputs(results, out_dir)
%WRITE_SUMMARY_OUTPUTS Save CSV, MAT, and LaTeX versions of the table.
%
% The LaTeX table is transposed for readability on A4 pages: scenarios are
% columns and economic indicators are rows.

    if ~exist(out_dir, 'dir')
        mkdir(out_dir);
    end

    full_csv = fullfile(out_dir, 'summary_table_full.csv');
    save(fullfile(out_dir, 'summary_table_workspace.mat'), 'results');
    writetable(results, full_csv);

    ok = results;
    if any(strcmp(ok.Properties.VariableNames, 'Status'))
        ok = ok(ok.Status == "ok", :);
    end

    tex_file = fullfile(out_dir, 'summary_table_for_paper.tex');
    write_latex_table_transposed(ok, tex_file);

    % Keep a second copy with an explicit filename, useful when comparing
    % versions of the paper table.
    tex_file_transposed = fullfile(out_dir, 'summary_table_for_paper_transposed.tex');
    write_latex_table_transposed(ok, tex_file_transposed);
end

function write_latex_table_transposed(T, tex_file)
    fid = fopen(tex_file, 'w');
    if fid < 0
        error('Unable to open %s for writing.', tex_file);
    end
    cleaner = onCleanup(@() fclose(fid)); %#ok<NASGU>

    nscen = height(T);
    if nscen == 0
        error('No successful scenarios available for the LaTeX table.');
    end

    scenario_labels = strings(1, nscen);
    for c = 1:nscen
        scenario_labels(c) = short_scenario_label(string(T.Scenario(c)));
    end

    fprintf(fid, '%% Auto-generated by summary_table/write_summary_outputs.m\n');
    fprintf(fid, '%% Requires \\usepackage{booktabs}\n');
    fprintf(fid, '\\begin{table}[!htbp]\n');
    fprintf(fid, '\\centering\n');
    fprintf(fid, '\\caption{Summary statistics for simulated optimal load-following policies.}\n');
    fprintf(fid, '\\label{tab:numerical-summary}\n');
    fprintf(fid, '\\begin{tabular}{l%s}\n', repmat('r', 1, nscen));
    fprintf(fid, '\\toprule\n');
    fprintf(fid, 'Metric');
    for c = 1:nscen
        fprintf(fid, ' & %s', escape_latex(char(scenario_labels(c))));
    end
    fprintf(fid, ' \\\\ \n');
    fprintf(fid, '\\midrule\n');

    % Core economic outcomes. The time-share and energy-volume rows are kept
    % separate to avoid interpreting frequent small deviations as large energy
    % imbalances.
    write_metric_row(fid, T, 'Total cost', 'TotalCost', 'number');
    write_metric_row(fid, T, 'Running cost', 'RunningCost', 'number');
    write_metric_row(fid, T, 'Switching cost', 'SwitchingCost', 'number');
    write_metric_row(fid, T, '$|P-Y|$ average', 'AvgAbsTrackingError', 'number');
    write_metric_row(fid, T, 'Shortage energy', 'ShortageEnergy', 'number');
    write_metric_row(fid, T, 'Excess energy', 'ExcessEnergy', 'number');
    write_metric_row(fid, T, 'Shortage time', 'ShortageTimeSharePct', 'percent');
    write_metric_row(fid, T, 'Excess time', 'ExcessTimeSharePct', 'percent');
    write_metric_row(fid, T, 'Number of switches', 'NumSwitches', 'integer');
    write_bound_row(fid, T);
    write_metric_row(fid, T, 'Purchases energy', 'PurchasesEnergy', 'number_or_dash');
    write_metric_row(fid, T, 'Sales energy', 'SalesEnergy', 'number_or_dash');
    write_metric_row(fid, T, 'Purchase cost', 'PurchaseCost', 'number_or_dash');
    write_metric_row(fid, T, 'Sales revenue', 'SalesRevenue', 'number_or_dash');

    fprintf(fid, '\\bottomrule\n');
    fprintf(fid, '\\end{tabular}\n');
    fprintf(fid, '\\vspace{0.5em}\n');
    fprintf(fid, ['\\parbox{0.94\\textwidth}{\\small Notes: All quantities are computed on the simulated paths. ', ...
        'Total cost is normalized and includes running and switching costs. ', ...
        '$|P-Y|$ is the time-average absolute tracking error. ', ...
        'Shortage and excess energy are time integrals of $(Y_t-P_t)^+$ and $(P_t-Y_t)^+$, respectively. ', ...
        'Shortage and excess time are percentages of simulated time, not energy volumes. ', ...
        'At bounds is the combined percentage of time at $P^{\\min}$ or $P^{\\max}$. ', ...
        'Purchases and sales are reported only for the open-economy scenarios. ', ...
        'Cost levels are normalized and should be compared within a given modelling environment rather than interpreted as monetary estimates.}\n']);
    fprintf(fid, '\\end{table}\n');
end

function write_metric_row(fid, T, label, variable_name, format_type)
    fprintf(fid, '%s', label);
    for r = 1:height(T)
        value = T.(variable_name)(r);
        fprintf(fid, ' & %s', format_value(value, format_type));
    end
    fprintf(fid, ' \\\\ \n');
end

function write_bound_row(fid, T)
    fprintf(fid, 'At bounds');
    for r = 1:height(T)
        value = T.TimeAtPminSharePct(r) + T.TimeAtPmaxSharePct(r);
        fprintf(fid, ' & %s', format_value(value, 'percent'));
    end
    fprintf(fid, ' \\\\ \n');
end

function out = format_value(value, format_type)
    if ismissing_numeric(value)
        out = '--';
        return;
    end

    switch char(format_type)
        case 'integer'
            out = sprintf('%.0f', value);
        case 'percent'
            out = sprintf('%.2f\\%%', value);
        case 'number_or_dash'
            out = sprintf('%.4g', value);
        otherwise
            out = sprintf('%.4g', value);
    end
end

function tf = ismissing_numeric(value)
    tf = isempty(value) || isnan(value) || isinf(value);
end

function label = short_scenario_label(scenario_name)
    s = lower(char(scenario_name));
    if contains(s, 'closed')
        label = "Closed";
    elseif contains(s, 'price taker')
        label = "Price taker";
    elseif contains(s, 'price maker') || contains(s, 'equilibrium')
        label = "Price maker";
    else
        label = scenario_name;
    end
end

function s = escape_latex(s)
    s = strrep(s, '\', '\textbackslash{}');
    s = strrep(s, '&', '\&');
    s = strrep(s, '%', '\%');
    s = strrep(s, '$', '\$');
    s = strrep(s, '#', '\#');
    s = strrep(s, '_', '\_');
    s = strrep(s, '{', '\{');
    s = strrep(s, '}', '\}');
    s = strrep(s, '~', '\textasciitilde{}');
    s = strrep(s, '^', '\textasciicircum{}');
end
